spring:
  redis:
    pool:
      min-idle: 0
      max-idle: 8
      max-active: 8
    port: 6379
    host: 127.0.0.1
  session:
    store-type: jdbc
  profiles:
    include: oauth
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://localhost:3306/board?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
  datasource: #db설정
    url: jdbc:h2:mem:testdb;
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true  #h2 콘솔 사용 가능하게 해줌
  jpa:
    show-sql: true   #쿼리 작동 시 sql문 출력해줌
    properties:
      hibernate:
        dialect:
          nodeValue: org.hibernate.dialect.MySQL57Dialect
          storage_engine: innodb
        default_batch_fetch_size: 1000
      datasource:
        hikari:
          jdbc-url: jdbc:h2:mem:testdb;MODE=MYSQL; #h2가 MYSQL 쿼리 인식할 수 있게 해줌
    hibernate:
      ddl-auto: create
  thymeleaf:
    cache: false
    check-template-location: true
    prefix: classpath:/templates/
    suffix: .html
    cache=false: false
  data:
    web:
      pageable:
        one-indexed-parameters: true
  servlet:
    multipart:
      enabled: true
      max-request-size: 20MB
      max-file-size: 20MB