--insert into category (CREATED_AT, type) values (now(), 'FREE');
--
--insert into category (CREATED_AT, type) values (now(), 'HUMOR');
--
--insert into category (CREATED_AT, type) values (now(), 'GAME');
--
--insert into category (CREATED_AT, type) values (now(), 'SPORT');
--
--insert into category (CREATED_AT, type) values (now(), 'IT');
--
--insert into category (CREATED_AT, type) values (now(), 'FOOD');
--
--insert into category (CREATED_AT, type) values (now(), 'QUESTION');
--
--insert into users (CREATED_AT, MODIFIED_AT, email, name, nickname, role, picture) values (now(), now(), 'spahb0563@naver.com', '문성준', 'spahb0563', 'USER', 'https://phinf.pstatic.net/contact/20221013_258/1665652589559BuAKX_GIF/image.gif');
--insert into users (CREATED_AT, MODIFIED_AT, email, name, nickname, role, picture) values (now(), now(), 'four0564@gmail.com', 'spahb 0563', 'spahb 0563', 'USER', 'https://lh3.googleusercontent.com/a/ALm5wu3BY6ZeyBncqWXBSorObYhGGBPhm6FMdD4UlmL60g=s96-c');

--insert into file (created_at, name, path, saved_name, size, type) values (now(), '183f8d44193efc0.jpg', 'C:/Users/msh/Desktop/img/c8bd94af-10bb-4889-bf18-d807d60d580f183f8d44193efc0.jpg', 'c8bd94af-10bb-4889-bf18-d807d60d580f183f8d44193efc0.jpg', ?, ?);
--insert into post (id, category_id, content, created_at, deleted_at, dislike_count, like_count, modified_at, opinion_count, title, users_id, view_count) values (default, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
--insert into post (CREATED_AT, MODIFIED_AT, CONTENT, OPINION_COUNT, TITLE, VIEW_COUNT, LIKE_COUNT, DISLIKE_COUNT, CATEGORY_ID, USERS_ID) values (now(), now(), 'test content test content test content test content test content test content test content test content test content test content test content test content test content test content test content test content test content test content  1', 0, '테스트용 게시물 타이틀입니다.', 0, 0, 0, 1, 1);
